### ISSUE TITLE
Re-assign the value to safe defaults instead of keeping the same value from previous run

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#108]
1) In the first test case if the user has updated a field to some value, there is no option to update the field to "Auto" again if applicable.
2) Have to clear the config in order to achieve this.

**Comment by ajbalogh** [comment]
There should be no need to clear the config. If a packet header field is specified the user is indicating the intent for the field to be set to that value. If the packet header is subsequently set but the field is omitted then it should be set to the traffic generator's default value since the user has indicated they don't care what the value is.

**Comment by ashutshkumr** [comment]
I think not providing value for length field here means that implementation should pick safe defaults for that field. And hence `Auto` choice shouldn't be required.

For some fields like `UDP source port` the default can be a particular value, not necessarily dependant on anything.

But for other fields like `length` which rely solely on packet layout, I think implementation should assign correctly calculated value to it (instead of using last assigned value).

So if I understand correctly, the issue is that last point doesn't hold true with IxN implementation.

**Comment by alakendu** [comment]
issue got fix waiting for review of https://github.com/open-traffic-generator/ixnetwork/pull/136
