### ISSUE TITLE
Traffic transmit state shows always 'started' for fixed flow even though the flow stops after transmitting all packets if there is other flow(continuous) in started state

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/ixnetwork#161]
Scenario - 1
Consider two flows f1 & f2 
1) f1 with fixed packet count
2) f2 with fixed packet count
<b>Transmit state once all packets are transmitted
stopped
stopped</b>

Scenario - 2
Consider two flows f1 & f2 
1) f1 with fixed packet count
2) f2 with continuous packet count
<b>Transmit state once packets are transmitted for f1
started
started</b>

<b>Note</b>: The traffic is not stopped intentionally in any Scenario

I assume, in scenario 2 the f1 state should be in stopped instead of started state as all packets are transmitted. When I dig deeper the states are coming from REST API, raising an issue as a counter issue for any customer use case

**Comment by ajbalogh** [comment]
This is a bug in ixnetwork middleware and can be reproduced by using the full UI and creating two traffic items, one continuous, the other stopping after a predefined number of packets.  This package will have to workaround that issue when returning flow stats. There is currently code in there to check the Tx Frame Rate and return started if it is greater than 0.  That section should be expanded to check the configelement rate and adjust the state based on frames tx etc.
At the same time a bug should be opened with ixnetwork traffic but the customer cannot wait for an update/hotfix/patch etc.
This issue is being seen by the current sonic use cases.

**Comment by ANISH-GOTTAPU** [comment]
test script
[test_traffic_transmit_state.zip](https://github.com/open-traffic-generator/ixnetwork/files/5696562/test_traffic_transmit_state.zip)

**Comment by ashutshkumr** [comment]
Verfied using test_traffic_transmit_state.py
