### ISSUE TITLE
Upload otg file in IxNet server and retrieve at the time of get_config

### ISSUE THREAD

**Issue by alakendu** [open-traffic-generator/ixnetwork#279]
Current get_config will not work if access IxNetwork server from different snappi_ixnetwork client. It will resolve if we will implement some converter from IxNetwork config to OTG config. But that will require more planning and time to implement. 

So I feel it will resolve if we upload otg file in IxNet server at the time of set_config and retrieve at the time of get_config. We should consider customer should configure IxNetwork through our snappi_ixnetwork client.

we will also need to push a .lockfile (just some empty file) to avoid contention with concurrent access

**Comment by ashutshkumr** [comment]
@ankur-sheth @ajbalogh @winstonliu1111 @ANISH-GOTTAPU @Rangababu-R

**Comment by ajbalogh** [comment]
I'm assuming this request originates from a customer use case where the gnmi service docker implementation needs to get configuration information in order to complete its metric requests/subscriptions - per @hashwini-keysight.  Instead of storing config information for this use case on the ixnetwork api server the gnmi service should request config from the otg config service. 
I will close this issue unless this is not the customer use case.
