### ISSUE TITLE
class variables and dict string names and index

### ISSUE THREAD

**Issue by ByReaL** [open-traffic-generator/ixnetwork#65]
taken from sample
column_names=['name', 'location', 'frames_tx', 'frames_rx'])

in my opinion, the strings should allow nice human-readable names like 'Frames Tx' 
and accessing it should work like obj['Frames Tx'] or obj.frames_tx or obj[0]

so as a string and dict name we should use a nice human-readable name, but when accessing it as a class variable we should do a lowercase and replace " " and other chars not allowed in variable naming with _ 
also, allow access by index.

**Comment by ashutshkumr** [comment]
@ajbalogh could you please review?

**Comment by ajbalogh** [comment]
Snappi is auto generated from an openapi docuemnt. 
The generated classes offers auto generated constants to specify column names and should be used instead of string constants (which is still valid if a user wants to specify that).
The document dictates that the returned metrics are encapsulated in a container class which supports python __next__ for row iteration support and __item__ which allows row by index access.
Once a row is retrieved users can access individual cells using the property accessor generated using the name from the models and made available to users with intellisense and docstring support.
Currently there is no support in the openapi models for alternate human readable names.
